# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BankHome' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BankHome

pod "Firebase"
pod "Firebase/RemoteConfig"
pod "SkeletonUI"

  target 'BankHomeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BankHomeUITests' do
    # Pods for testing
  end

end
